name: Checks, linting and tests for CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  yarn:
    name: Cache of yarn matches checksums in lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn --immutable --immutable-cache --check-cache

  build:
    name: Build succeeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn --immutable --immutable-cache
      - run: yarn build

  prettier:
    name: Prettier: All source files are well formated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn --immutable --immutable-cache
      - run: yarn lint:prettier

  tsc:
    name: TypeScript compiles
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn --immutable --immutable-cache
      - run: yarn lint:tsc

  eslint:
    name: eslint has no errors
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn --immutable --immutable-cache
      - run: yarn lint:eslint
